export function buttonStyleCommandSeries(): string[][] {
  return [
    [
      'ui',
      'component',
      'update',
      'button',
      'bem',
      'block',
      'style',
      'declare',
      '--base',
      'background: white; transition: $transition',
      '--hover',
      'background: black',
    ],
    [
      'ui',
      'component',
      'update',
      'button',
      'bem',
      'element',
      'style',
      'declare',
      'text',
      '--state',
      'hover',
      '--base',
      'color: white',
    ],
    [
      'ui',
      'component',
      'update',
      'button',
      'bem',
      'element',
      'style',
      'declare',
      'icon',
      '--base',
      'width: 16px; aspect-ratio: 1 / 1; height: 16px',
    ],
    [
      'ui',
      'component',
      'update',
      'button',
      'bem',
      'element',
      'style',
      'declare',
      'text',
      '--base',
      'font-size: 16px; color: black',
    ],
    [
      'ui',
      'component',
      'update',
      'button',
      'bem',
      'element',
      'style',
      'declare',
      'text',
      '--media',
      'tablet',
      '--base',
      'font-size: 14px',
    ],
    [
      'ui',
      'component',
      'update',
      'button',
      'bem',
      'element',
      'style',
      'declare',
      'text',
      '--media',
      'mobile',
      '--base',
      'font-size: 12px',
    ],
  ]
}
