import { buttonStyleCommandSeries } from './button-style-commands.ts'

export function buttonTemplateCommandSeries(): string[][] {
  return [
    ['ui', 'component', 'create', 'button'],
    [
      'ui',
      'component',
      'update',
      'button',
      'prop',
      'group',
      'create',
      'ButtonProps',
      '--extends',
      'HTMLAttributes<button>',
    ],
    ['ui', 'component', 'update', 'button', 'prop', 'group', 'create', 'AnchorProps', '--extends', 'HTMLAttributes<a>'],
    ['ui', 'component', 'update', 'button', 'prop', 'create', 'tag', 'button | div | span', '--group', 'ButtonProps'],
    [
      'ui',
      'component',
      'update',
      'button',
      'prop',
      'create',
      'href',
      'never',
      '--group',
      'ButtonProps',
      '--no-destructure',
    ],
    ['ui', 'component', 'update', 'button', 'prop', 'create', 'tag', 'a', '--group', 'AnchorProps'],
    [
      'ui',
      'component',
      'update',
      'button',
      'prop',
      'create',
      'href',
      'string',
      '--group',
      'AnchorProps',
      '--required',
      '--no-destructure',
    ],
    ['ui', 'component', 'update', 'button', 'prop', 'create', 'variant', 'contained | text', 'contained'],
    ['ui', 'component', 'update', 'button', 'prop', 'create', 'color', 'green | white', 'green'],
    ['ui', 'component', 'update', 'button', 'prop', 'create', 'iconStart', 'IconKey'],
    ['ui', 'component', 'update', 'button', 'prop', 'create', 'iconEnd', 'IconKey'],
    ['ui', 'component', 'update', 'button', 'prop', 'create', 'text', 'string'],
    ['ui', 'component', 'update', 'button', 'root', 'append', '--node', '1.1', '--tag', 'span', '--name', 'text'],
    ['ui', 'component', 'update', 'button', 'root', 'append', '--node', '1.1.1', '--expression', 'text'],
    [
      'ui',
      'component',
      'update',
      'button',
      'root',
      'prepend',
      '--node',
      '1.1',
      '--tag',
      'span',
      '--name',
      'icon',
      '--sibling',
      'text',
    ],
    [
      'ui',
      'component',
      'update',
      'button',
      'root',
      'append',
      '--node',
      '1.1',
      '--tag',
      'span',
      '--name',
      'icon',
      '--sibling',
      'text',
    ],
    [
      'ui',
      'component',
      'update',
      'button',
      'root',
      'append',
      '--node',
      '1.1.3',
      '--component',
      'Icon',
      '--condition',
      'iconEnd',
      '--prop',
      'name=iconEnd',
    ],
    [
      'ui',
      'component',
      'update',
      'button',
      'root',
      'append',
      '--node',
      '1.1.1',
      '--component',
      'Icon',
      '--condition',
      'iconStart',
      '--prop',
      'name=iconStart',
    ],
    ...buttonStyleCommandSeries(),
  ]
}
