export const componentUpdateDescription = [
  'Run a Starfront UI component update through the structured MCP tool. Prefer specific tools such as ui_component_root_append, ui_component_bem_element_style_declare, ui_component_bem_element_style_delete, ui_component_bem_modifier_classlist_add, ui_component_bem_modifier_style_declare, ui_component_bem_modifier_style_delete, ui_component_bem_block_style_delete, ui_component_root_delete, ui_component_prop_create, ui_component_prop_update, ui_component_prop_delete, and ui_component_prop_group_create when they fit. Use this generic tool only for update grammar not covered by a specific tool. Equivalent CLI form is starfront ui component update <name> <tokens...>; tokens contains only arguments after <name>.',
  'Supported tokens:',
  'root append|prepend with options.node and one of options.tag, options.component, options.isSlot, options.text, or options.expression; use options.slotName only with options.isSlot true;',
  'root clear;',
  'root delete with options.node;',
  'root set with replacement root options;',
  'root attr set with options.name and options.value;',
  'root classlist add with options.value;',
  'root slot append|wrap with slot options;',
  'prop create <propName> <type> [defaultValue] with optional options.required, options.group, options.destructure;',
  'prop update <propName> [type] [defaultValue] with optional options.required, options.group, options.destructure;',
  'prop delete <propName> with optional options.group;',
  'prop group create <groupName> with options.extends;',
  'bem element style declare <elementName> with declaration options;',
  'bem element style delete <elementName> with options.media or options.state;',
  'bem modifier classlist add <modifierName> with options.propName, options.value, or options.expression;',
  'bem modifier style declare <modifierName> with options.value and declaration options; modifier value styles are nested, for example &_variant { &-primary { ... } }, so use modifierName variant with options.value primary instead of modifierName variant-primary;',
  'bem modifier style delete <modifierName> with options.value, options.media, or options.state;',
  'bem block style declare with declaration options;',
  'bem block style delete with options.state.',
].join(' ')
